In [1]:
import numpy as np

In [2]:
np.array([2,3,4,5,6])

array([2, 3, 4, 5, 6])

In [3]:
type(np.array([2,3,4,5,6]))

numpy.ndarray

In [4]:
l = [[1,2,3,4] , [ 2,3,4,5]]

In [6]:
l[1][3]

5

In [7]:
np.random.randint(1,10,(4,4,2))

array([[[2, 7],
        [8, 8],
        [4, 4],
        [2, 7]],

       [[9, 1],
        [6, 8],
        [8, 8],
        [1, 4]],

       [[8, 2],
        [3, 2],
        [5, 3],
        [2, 2]],

       [[8, 4],
        [7, 8],
        [7, 9],
        [3, 3]]])

##check the visual representation of array idea in the last part of the pandas class

#task 2 - Superstore_USA
1 . load this data in sql and in pandas with a relation in sql 
2 . while loading this data you dont have to create a table manually you can use any automated approach to create a table and load a data in bulk in table 
3 . Find out how return that we ahve recived and with a product id 
4 . try  to join order and return data both in sql and pandas 
5 . Try to find out how many unique customer that we have 
6 . try to find out in how many regions we are selling a product and who is a manager for a respective region 
7 . find out how many different differnet shipement mode that we have and what is a percentage usablity of all the shipment mode with respect to dataset 
8 . Create a new coulmn and try to find our a diffrence between order date and shipment date
9 . base on question number 8 find out for which order id we have shipment duration more than 10 days 
10 . Try to find out a list of a returned order which sihpment duration was more then 15 days and find out that region manager as well 
11 . Gorup by region and find out which region is more profitable 
12 . Try to find out overalll in which country we are giving more didscount 
13 . Give me a list of unique postal code 
14 . which customer segement is more profitalble find it out . 
15 . try to find out the 10th most loss making product catagory . 
16 . Try to find out 10 top  product with highest margins 

submit your git link for the same 
 
you have to submit this task by next Friday 5th 11PM IST  to respective mail id 
sudhanshu@ineuron.ai , sunny.savita@ineuron.ai 

In [8]:
l1 = [1,3,4,'dfdsf', 34.4, True]

In [9]:
np.array(l1)

array(['1', '3', '4', 'dfdsf', '34.4', 'True'], dtype='<U32')

In [13]:
np.random.randint(1,50, (2,3,4))

array([[[43,  7, 27, 36],
        [25, 28, 41, 36],
        [ 2, 22, 46, 26]],

       [[12, 12, 11, 42],
        [29, 45, 20, 30],
        [17, 41, 28, 31]]])

In [14]:
a4 = np.random.randn(4,4)

In [15]:
a4

array([[ 0.94431923,  1.55153823,  0.00216433,  0.66990479],
       [-1.16372692,  1.6613517 , -0.89849468, -0.51929957],
       [ 0.09183027, -0.44045727,  0.67425483,  1.61655581],
       [ 1.26148577,  0.57142987, -0.27760314, -1.27740876]])

In [16]:
a4.reshape(16,1)

array([[ 0.94431923],
       [ 1.55153823],
       [ 0.00216433],
       [ 0.66990479],
       [-1.16372692],
       [ 1.6613517 ],
       [-0.89849468],
       [-0.51929957],
       [ 0.09183027],
       [-0.44045727],
       [ 0.67425483],
       [ 1.61655581],
       [ 1.26148577],
       [ 0.57142987],
       [-0.27760314],
       [-1.27740876]])

In [19]:
a5 = np.random.randint(2,90, (6,5))

In [20]:
a5

array([[39, 13, 39, 54, 62],
       [83,  7, 16, 50, 85],
       [84, 77, 80,  9,  5],
       [26, 17, 48, 62, 71],
       [47, 43, 18, 51,  3],
       [42, 53, 71, 66, 62]])

In [22]:
a5[a5>40]

array([54, 62, 83, 50, 85, 84, 77, 80, 48, 62, 71, 47, 43, 51, 42, 53, 71,
       66, 62])

In [23]:
a = np.array([1,2,3,4])

In [24]:
a

array([1, 2, 3, 4])

In [30]:
b = np.array([[1,2,3,4]]).T

In [31]:
b

array([[1],
       [2],
       [3],
       [4]])

In [32]:
np.arange(1,10,1.5)

array([1. , 2.5, 4. , 5.5, 7. , 8.5])